# Generated by Django 3.2.25 on 2024-03-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='like_count',
        ),
    ]
